/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_duke_biac_srb_SRBInputStream */

#ifndef _Included_edu_duke_biac_srb_SRBInputStream
#define _Included_edu_duke_biac_srb_SRBInputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_duke_biac_srb_SRBInputStream
 * Method:    read
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_edu_duke_biac_srb_SRBInputStream_read
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
