/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_duke_biac_srb_SRBURLConnection */

#ifndef _Included_edu_duke_biac_srb_SRBURLConnection
#define _Included_edu_duke_biac_srb_SRBURLConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_duke_biac_srb_SRBURLConnection
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_duke_biac_srb_SRBURLConnection_connect
  (JNIEnv *, jobject);

/*
 * Class:     edu_duke_biac_srb_SRBURLConnection
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_duke_biac_srb_SRBURLConnection_disconnect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
